services:
  - type: web
    name: chatpoint-sindagi
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      NODE_VERSION: ~20
      PORT: 3000
      JWT_SECRET: chatpoint_super_secret_key_2025
      MONGODB_URI:
        fromDatabase:
          name: chatpoint-db
          property: connectionString
databases:
  - name: chatpoint-db
    plan: free